### ISSUE TITLE
version_id parameter must be an integer

### ISSUE THREAD

**Issue by lloeki** [actions/delete-package-versions#101]
So I'm hitting this strange issue I can't quite explain when deleting a package version on `ghcr.io`:

```
Error: delete version API failed. The version_id parameter must be an integer. 
```

Full output:

```
Run actions/delete-package-versions@v4
  with:
    package-version-ids: gha4622410040-g3d94762cffc166ff549a28c3710ca44cdddc4f2a
    package-name: system-tests/runner
    package-type: container
    num-old-versions-to-delete: 1
    min-versions-to-keep: -1
    ignore-versions: ^$
    delete-only-pre-release-versions: false
    delete-only-untagged-versions: false
    token: ***
  env:
    REGISTRY: ghcr.io
Total versions deleted till now: 1
Error: delete version API failed. The version_id parameter must be an integer. 
0 versions deleted till now.
```

Usage in workflow:

```
    steps:
      ...
      - uses: actions/delete-package-versions@v4
        with:
          package-version-ids: gha${{ github.run_id }}-g${{ github.sha }}
          package-name: system-tests/${{ matrix.image }}
          package-type: 'container'
        continue-on-error: true
```

**Comment by pbaroni-mdlz** [comment]
same issue here, version is 1.1.17

**Comment by rlaiola** [comment]
I managed to get `actions/delete-package-versions@v4` working using the actual version id on `ghcr.io` (**not the digest**). In order to obtain that for a package owned by a user, see the documentation [here](https://docs.github.com/en/rest/packages?apiVersion=2022-11-28#list-package-versions-for-a-package-owned-by-a-user).

### Listing package versions for a package owned by a user (cURL):
```sh
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/users/USERNAME/packages/PACKAGE_TYPE/PACKAGE_NAME/versions
````

Example (replace `<YOUR-TOKEN>` accordingly):

```sh
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/users/rlaiola/packages/container/relax-docker/versions
````

A JSON will be returned. You need an id like the one in the image below.

<img width="833" alt="Screen Shot 2023-05-16 at 20 51 24" src="https://github.com/actions/delete-package-versions/assets/4059310/f5fafd98-7633-4f63-b4f6-f7c238db5b78">

Hope it helps!

Cheers.

**Comment by pbaroni-mdlz** [comment]
> same issue here, version is 1.1.17

Using "Version ID" instead of "Version", it worked:

![image](https://github.com/actions/delete-package-versions/assets/102743297/ff1c5b17-3c1c-4926-b5a8-07026418be75)

**Comment by derpda** [comment]
The documentation specifically lists below example
```
- uses: actions/delete-package-versions@v4
  with:
    package-version-ids: 'MDE0OlBhY2thZ2VWZXJzaW9uOTcyMDY3'
    package-name: 'test-package'
    package-type: 'npm'
```
As in, a string should be accepted, so this seems to be a bug.

As suggested in the same Readme, I get that string from the GitHub GraphQL API, not sure that an int version is even available there. 
If there is an int verison, could someone let me know how to acquire it?
