### ISSUE TITLE
Error: get versions API failed. Package not found.

### ISSUE THREAD

**Issue by batulziiy** [actions/delete-package-versions#115]
Hello, 

Currently I'm trying to create a job to delete old images other than the last 5. There are 2 exact same jobs set and one fails with the error message `get versions API failed. Package not found.`. I don't see any difference between these 2 packages except for visibility (one is private while another one is public). Here are some details  : 

Env : Github Enterprise Server 3.10
Package type : container
Package version : v2
TOKEN created? : yes. I've created organization secret variable for PAT (PAT has permission to read, delete packages)

delete-package-versions job : 
```
on:
  schedule:
    - cron: '0 12 * * 1'
jobs:
  delete-old-images:
    runs-on: self-hosted
    steps:
      - name: Keep the last 5
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'metrics'
          package-type: 'container'
          min-versions-to-keep: 5
          token: ${{ secrets.DELETE_PACKAGE_TOKEN }}
```

I tried to compare 2 packages details by getting packages details via API and the details look identical except for organization and visibility. Any help would be appreciated. Thanks.
