### ISSUE TITLE
`min-versions-to-keep` behaviour inconsistent with documentation

### ISSUE THREAD

**Issue by vpipkt** [actions/delete-package-versions#116]
## Scenario and intent

I am using GH Packages for docker images. I am writing a very simple workflow with this action, targeting my docker image artifacts. My intent is to implement the [retention policy pattern shown in this section of the readme](https://github.com/actions/delete-package-versions#delete-all-except-y-latest-versions-of-a-package).

Here is the workflow.job.step I am using:

```yaml
      - uses: actions/delete-package-versions@v4
        id: delete-packages-web
        with:
          package-name: web
          package-type: container
          min-versions-to-keep: 3
```

Following from the readme, I do not supply the `num-old-versions-to-delete`:

>  By default, `min-versions-to-keep` takes precedence over `num-old-versions-to-delete`.

## Expected behaviour

I expect as the Readme states: the Action will delete all except latest 3 versions of the package.

## Actual behaviour

The action deletes all but the latest 1 version of the package. The resulting behaviour is what I would expect if  I had set  `num-old-versions-to-delete: 1`  **and** that parameter took precedence over `min-versions-to-keep`.
