### ISSUE TITLE
ignore-versions doesn't work

### ISSUE THREAD

**Issue by lukjaki** [actions/delete-package-versions#120]
I'm trying to set this action to remove certain packages but I want to keep all semver-correct versions. For instance `1.8.0-develop-312` should be deleted but `1.8.0` should persist. 

My action setup is as follows:
```
package-name: xxx-xxx-xxx
package-type: npm
ignore-versions: '^(0|[1-9]\d*)\\.0\\.0$'
min-versions-to-keep: 10
```

but it keeps deleting all packages.

What am I doing wrong?

**Comment by ruben-hoenle-fnt** [comment]
same for me, this action is not usable in it's current state

**Comment by SaurabhKoverhoop** [comment]
same issue - specific versions that were to be ignored got deleted

**Comment by emmahsax** [comment]
I'm getting the same issue as well. This is my job:

```yaml
      - uses: actions/delete-package-versions@v4
        with:
          ignore-versions: '.*main-ci.*'
          min-versions-to-keep: 5
          package-name: ${{ github.event.repository.name }}
          package-type: container

```

I've tried `'.*main-ci.*'` as shown, I've tried `'main-ci'`, `'^main-ci$'`, etc... it continues to delete that package. It's very frustrating.
