### ISSUE TITLE
Delete oldest x number of versions of a package but keep a minimum

### ISSUE THREAD

**Issue by jaschaio** [actions/delete-package-versions#17]
Honestly this could probably be more easily accomplished with implementing https://github.com/actions/delete-package-versions/issues/5 (keep only N latest versions of package) but how would I keep a minimum number of versions of a package?

If I just use the example:

```yml
- uses: actions/delete-package-versions@v1
  with:
    package-name: 'test-package'
    num-old-versions-to-delete: 10
```

This would delete the 10 oldest version. But what if I only have 8 versions?

What if I want to at least keep the last three versions around?
