### ISSUE TITLE
All packages get deleted recursively

### ISSUE THREAD

**Issue by mddanishansari** [actions/delete-package-versions#18]
Hello developers, 

Hope you're having a nice day. I got a problem while using this action which I have described below

I have created an action where I want to delete the oldest version of the same package which is updated. 

Let's say I have 3 versions 1.0, 1.1, 1.2 and then when I update the package to v1.4, v1.0 should get deleted. But I realized that with each delete, same action is triggered again and it goes in infinite loop.

So is there any workaround for this? May be you include a new type like `new_version` or something. Just an idea.

Content of YAML file looks something like this

```
name: Delete oldest package

on:
  registry_package:
   type: [updated]

jobs:
  delete_package:
    runs-on: ubuntu-latest
    steps:
      - name: Delete package version
        uses: actions/delete-package-versions@v1.0.2
        with:
          package-name: com.md.calculator
          num-old-versions-to-delete: 1

```
