### ISSUE TITLE
provide a new config/input:  version-patterns

### ISSUE THREAD

**Issue by tomsit-ionos** [actions/delete-package-versions#228]
Sometimes it's much easier to define a list of positive matches of versions u want to delete instead of a single negative match regex. 
B/c if u screw up that pattern, it might match way too much and will deleted version that u did not intend.

Hence i propose the following (alternative) input(s):

```yaml
with:
  - include-version-patterns:
    - .*SNAPSHOT.*
    - .*alpha.*
````

#### Bonus

As the above examples already show, a list of positive patterns tends to focus on the existence of a substring. Therefore it might make sense to have these inputs:

```yaml
with:
  - version-contains: #  version will be deleted if any of the patterns is contained
    - '-SNAPSHOT'
    - 'alpha'
  - version-matches: # version will be deleted  if it fully matches any of the patterns and thus implies `^<my-regex>$`
    - .*SNAPSHOT.*
    - .*alpha.*
````

#### combine or mutex these  inputs ?
i personally think it's fine to AND all of the include/ignore inputs , but u may also chose to say, just one of these is allowed.
