### ISSUE TITLE
num-old-versions-to-delete: 1 deletes `docker-base-layer`

### ISSUE THREAD

**Issue by jcansdale** [actions/delete-package-versions#24]
After publishing 3 Docker images and using `num-old-versions-to-delete: 1`, I noticed that `docker-base-layer` was deleted rather than the oldest tag.

You can see it being deleted here:

![image](https://user-images.githubusercontent.com/11719160/88237894-337a0d00-cc78-11ea-8bc2-baa8046bc40d.png)

The `docker-base-layer` no longer exists here:
https://github.com/jcansdale-test/delete-package-versions/runs/900578034?check_suite_focus=true#step:12:11

The issue can be reproduced with the following workflow:

```yml
on: [push, workflow_dispatch]

env:
  IMAGE_NAME: image-to-delete

jobs:
  push-and-delete:
    runs-on: ubuntu-latest

    steps:
    - run: docker pull alpine

    - run: docker login https://docker.pkg.github.com -u token --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}

    - run: docker tag alpine:latest docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:0.1
    - run: docker tag alpine:latest docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:0.2
    - run: docker tag alpine:latest docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest

    - run: docker push docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:0.1
    - run: docker push docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:0.2
    - run: docker push docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest

    - run: docker run jcansdale/gpr files ${{ github.repository }} -k ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/delete-package-versions@v1
      with:
        package-name: ${{ env.IMAGE_NAME }}
        num-old-versions-to-delete: 1

    - run: docker run jcansdale/gpr files ${{ github.repository }} -k ${{ secrets.GITHUB_TOKEN }}
```
