### ISSUE TITLE
Improve documentation/examples for dynamic version ids

### ISSUE THREAD

**Issue by chrisjohnson00** [actions/delete-package-versions#32]
Perhaps I'm too much of a n00b, but I'm finding it difficult to get this working with dynamic version ids.

My use case is that I build and push a docker container for every branch.  The version (tag) on the container is the branch name.
What I'd like to do is delete the versions which match the branch name when I delete the branch.

Here's what I've attempted

```
name: Delete branch tag

on:
  delete:
    branches: [ '**' ]

jobs:
  cleanup:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-version-ids: ${GITHUB_REF##*/}
```

But this results in an error:

```
Error: delete version mutation failed. Could not resolve to a node with the global id of '${GITHUB_REF##*/}'
```

The docs/examples don't give enough help/direction on how to get the version ids other than telling me to go look at the GH APIs.  Is there a related action that I should use to get this, how have other people tackled deleting versions dynamically?
