### ISSUE TITLE
TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by Gutyerrez** [actions/delete-package-versions#39]
My configuration
```
    - name: Delete old versions of this packages
      uses: actions/delete-package-versions@main
      with:
        owner: hyrendev
        repo: nexus
        package-name: |
          com.redefantasy.core-bungee
          com.redefantasy.core-shared
          com.redefantasy.core-spigot
        token: ${{ secrets.ACCESS_TOKEN }}
```

Action output:

```
Run actions/delete-package-versions@main
  with:
    owner: hyrendev
    repo: nexus
    package-name: com.redefantasy.core-bungee
  com.redefantasy.core-shared
  com.redefantasy.core-spigot
  
    token: ***
    num-old-versions-to-delete: 1
  env:
    MAVEN_USERNAME: ***
    MAVEN_PASSWORD: ***
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.282-8/x64
```

Throws:

```
Error: TypeError: Cannot read property 'node' of undefined
```
