### ISSUE TITLE
Feature request:  Support deleting packages older than X days

### ISSUE THREAD

**Issue by mkrakowitzer** [actions/delete-package-versions#4]
Would like to suggest a feature where packages can be deleted that are older than X days.

Similar to this action for purging artifacts:
```
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days
```
