### ISSUE TITLE
Feature request: keep only N latest versions of the package

### ISSUE THREAD

**Issue by zmeyc** [actions/delete-package-versions#5]
It would be cool to have an option to keep only N latest versions of 'package-name' and deleting other versions.

It can be used in combination with date-based deletion https://github.com/actions/delete-package-versions/issues/4

**Comment by coronaction** [comment]
Voted for this one : it would really help if we could keep only N latest versions of a package. Thanks!

**Comment by didier-durand** [comment]
Yes, this feature would be highly useful

**Comment by sullrich84** [comment]
👍🏼 Came here to ask for this :)

**Comment by hazcod** [comment]
The Action does not make sense without this. Upvote!

**Comment by jonathanong-houzz** [comment]
similarly, i'd want say "last X versions and all versions less than 30 days old"

**Comment by rubengees** [comment]
Until this is implemented here, I wrote an action which is able to delete everything apart from a configurable number of latest packages (ordered by date desc): https://github.com/SmartsquareGmbH/delete-old-packages

**Comment by didier-durand** [comment]
Excellent!

**Comment by chingc** [comment]
This feature is the first thing I thought about when I found out about this action. I was actually surprised to find out it couldn't do it. Definitely upvoting, but I'm not too hopeful given this project hasn't been updated for quite some time...

**Comment by sandstrom** [comment]
Yes, would like to setup package deletion rule like this:

- Keep the N most recent versions, and
- keep all versions created in the past Y months.

(and delete all other versions)

**Comment by timofey-drozhzhin** [comment]
For now one workaround to limit the scope of deletion to the current version, is to use negative lookahead. For example, this config only deletes the packages tagged with the current branch, while only keeping the last 4.

```yaml
- name: Purge older packages
  uses: actions/delete-package-versions@v2
  with:
    package-name: "${{ github.event.repository.name }}"
    # Ignore all tags not matching this branch name
    ignore-versions: ^(?!${{ github.event.release.tag_name }})$
    min-versions-to-keep: 4
```
