### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by lewismoten** [actions/delete-package-versions#51]
I keep getting an error about an API rate limit.

`query for oldest version failed. API rate limit exceeded for installation ID 20433984.`

```yml
name: Delete Package Versions

on:
  push:
    branches:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    name: Remove 100
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "MY_REPO_NAME"
          package-name: "MY_REPO_NAME"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
```
