### ISSUE TITLE
Action failing with Unexpected input(s) 'min-versions-to-keep'.

### ISSUE THREAD

**Issue by OmarOmeiri** [actions/delete-package-versions#54]
I have a simple private package being published. Since I'm the only user, I don't want to bother with versioning and want to keep it as `v1.0.0` always.

My workflow is as follows:

```yml
name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'lullo-utils'
          min-versions-to-keep: 1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@LulloIO'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.LULLO_PKG_TOKENREADONLY}}
```

But the action fails with:
`Unexpected input(s) 'min-versions-to-keep', valid inputs are ['package-version-ids', 'owner', 'repo', 'package-name', 'num-old-versions-to-delete', 'token']`

I got this idea from the [README](https://github.com/actions/delete-package-versions#delete-all-except-y-latest-versions-of-a-package).

Is this some bug?
