### ISSUE TITLE
invalid input min-versions-to-keep

### ISSUE THREAD

**Issue by fobbyal** [actions/delete-package-versions#55]
I am getting the following warning with
```
    - uses: actions/delete-package-versions@v1
      with: 
        package-name: 'com.integ.auto-task'
        min-versions-to-keep: 35
        num-old-versions-to-delete: 0
```
![image](https://user-images.githubusercontent.com/7818365/143249978-82a11380-ffa2-48f9-ab74-3959507eeeee.png)
Not sure if need to reference a new version or something.
