### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by mmenozzi** [actions/delete-package-versions#57]
I'm trying to delete old package versions in a GitHub Actions workflow on private repository. Packages are under the same repository where GitHub Actions run. I can see them in the repository home page and by making API call with GH CLI.

**I'm using the autogenerated `GITHUB_TOKEN`**.

When I run the step with this action i get the following:

```
Run actions/delete-package-versions@v2
  with:
    package-name: sylius-project.php
    min-versions-to-keep: 5
    ignore-versions: latest
    num-old-versions-to-delete: 1
    delete-only-pre-release-versions: false
    token: ***

(node:35689) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
package: sylius-project.php not found for owner: webgriffe in repo: sylius-project
no package version ids found, no versions will be deleted
```

As you can see I get a deprecation warning but what is worst is that it says that the package `syliu-project.php` cannot be found for that repository.

I cannot understand why. Anyone could help me?
