### ISSUE TITLE
Need some help to configure variables

### ISSUE THREAD

**Issue by beeyev** [actions/delete-package-versions#76]
I use github packages to store docker images.
Imagine I have this package `ghcr.io/alpha/beta:latest`
When I execute this command: `docker pull ghcr.io/alpha/beta:latest` everything is working, it means that the package itself is correctly resolved.

So, according to the data I provided, what values should I set to variables: `owner, repo, package-name` ?

This configuration did not work for me:
```
      - name: Cleanup package registry
        uses: actions/delete-package-versions@v3
        with:
          owner: 'alpha'
          repo: 'beta'
          package-name: 'beta'
          token: ${{ secrets.GH_PAT_PACKAGES }}
          min-versions-to-keep: 2
```
