### ISSUE TITLE
Package not found when deleting oldest version of a package

### ISSUE THREAD

**Issue by y-meguro** [actions/delete-package-versions#77]
Hi.
Since yesterday I have not been able to delete a package, 2 days ago it was working correctly.

### My configuration
I want to [delete oldest version of a package](https://github.com/actions/delete-package-versions#delete-oldest-version-of-a-package).
```
      - name: delete oldest version of a package
        uses: actions/delete-package-versions@v3
        with:
          package-name: "shared-all"
```

### Output
```
Run actions/delete-package-versions@v3
  with:
    package-name: shared-all
    num-old-versions-to-delete: 1
    min-versions-to-keep: -1
    ignore-versions: ^$
    delete-only-pre-release-versions: false
    token: ***
package: shared-all not found for owner: Newt-Inc in repo: newt
```

I am not getting any errors, but I cannot find the package and delete it.

### My package info
- I use GitHub Packages Registry `https://npm.pkg.github.com`

---

I haven't changed any settings for the past two days.
Can you help fixing it?
